[package]
name = "amethyst_config"
version = "0.3.0"
authors = ["Aceeri <conmcclusk@gmail.com>"]
description = "Loading from .ron files into Rust structures with defaults to prevent hard errors."

documentation = "https://www.amethyst.rs/doc/master/amethyst_config/"
homepage = "https://www.amethyst.rs/"
repository = "https://github.com/amethyst/amethyst"

license = "MIT/Apache-2.0"

[badges]
appveyor = { repository = "amethyst/amethyst" }
travis-ci = { repository = "amethyst/amethyst" }

[dependencies]
ron = "0.1"
serde = "1.0"

[dev-dependencies]
serde_derive = "1"
