[package]
name = "amethyst_audio"
version = "0.5.0"
authors = ["Xaeroxe <kieseljake@gmail.com>"]
edition = "2018"
description = "Audio support for Amethyst"
exclude = ["examples/*"]
keywords = ["game", "engine", "audio","amethyst"]
categories = ["audio"]

documentation = "https://www.amethyst.rs/doc/latest/doc/amethyst_audio/"
homepage = "https://www.amethyst.rs/"
repository = "https://github.com/amethyst/amethyst"

readme = "README.md"
license = "MIT/Apache-2.0"

[badges]
appveyor = { repository = "amethyst/amethyst", branch = "master" }
travis-ci = { repository = "amethyst/amethyst" }

[dependencies]
amethyst_assets = { path = "../amethyst_assets", version = "0.6.0"}
amethyst_core = { path = "../amethyst_core", version = "0.5.0"}
amethyst_error = { path = "../amethyst_error", version = "0.1.0"}
amethyst_utils = { path = "../amethyst_utils", version = "0.5.0"}
cpal = "0.8"
log = "0.4.6"
rodio = "0.8"
serde = { version = "1.0", features = ["derive"] }

thread_profiler = { version = "0.3", optional = true }

[dependencies.smallvec]
version = "0.6"
features = ["serde"]

[features]
profiler = [ "thread_profiler/thread_profiler" ]
nightly = [ "amethyst_core/nightly" ]
