# Set up the build environment.
environment:
  matrix:
    - channel: stable
      target: x86_64-pc-windows-msvc
    - channel: beta
      target: x86_64-pc-windows-msvc
    - channel: nightly
      target: x86_64-pc-windows-msvc

# Allow for occasional compiler breakage on nightly Rust.
matrix:
  fast_finish: true
  allow_failures:
    - channel: nightly

install:
  # Set up the Rust toolchain.
  - set PATH=C:\Program Files\Git\mingw64\bin;%PATH%
  - curl -fsS "https://win.rustup.rs/" -o rustup-init.exe
  - rustup-init.exe -y --default-toolchain %channel%-%target%
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - rustc -V
  - cargo -V
  # download SDL2 dependency
  - appveyor DownloadFile https://www.libsdl.org/release/SDL2-devel-2.0.8-VC.zip
  - 7z x SDL2-devel-2.0.8-VC.zip
  - copy SDL2-2.0.8\lib\x64\*.lib C:\Users\appveyor\.multirust\toolchains\%channel%-%target%\lib\rustlib\%target%\lib
  - copy SDL2-2.0.8\lib\x64\*.dll .

# Build the Bors staging and trying branches, plus PRs to develop, master, and
# the latest release branch.
branches:
  only:
    - staging
    - trying
    - develop
    - master
    - /release-.*/

# Force third-party crates to persist from previous builds and update only when
# needed.
cache:
  - .cargo

# Since this is not a .NET project, we can flip the build system off.
build: false

# Generate documentation, compile the engine, run tests.
test_script:
  - cargo test --all -v
  - cargo test --all -v --features profiler
  - cargo test --all -v --features sdl_controller
