# Set up the build environment.
environment:
  matrix:
    - channel: stable
      target: x86_64-pc-windows-msvc
    - channel: beta
      target: x86_64-pc-windows-msvc
    - channel: nightly
      target: x86_64-pc-windows-msvc

# Allow for occasional compiler breakage on nightly Rust.
matrix:
  fast_finish: true
  allow_failures:
    - channel: nightly

# Set up the Rust toolchain.
install:
  - set PATH=C:\Program Files\Git\mingw64\bin;%PATH%
  - curl -fsS "https://win.rustup.rs/" -o rustup-init.exe
  - rustup-init.exe -y --default-toolchain %channel%-%target%
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - rustc -V
  - cargo -V

# Build the Bors staging and trying branches, plus PRs to develop, master, and
# the latest release branch.
branches:
  only:
    - staging
    - trying
    - develop
    - master
    - /release-.*/

# Force third-party crates to persist from previous builds and update only when
# needed.
cache:
  - .cargo -> rust-%channel%-date, cargo-%channel%-build

# Since this is not a .NET project, we can flip the build system off.
build: false

# Generate documentation, compile the engine, run tests.
test_script:
  - cargo run --release ci
