# Test suite must pass on both Travis and AppVeyor before merging into `master`.
status = [
    "continuous-integration/travis-ci/push"
]

# Do not allow pull requests with these labels to be merged.
block_labels = [
    "status: postponed",
    "status: stalled",
    "status: wontfix",
    "status: working"
]

# This feature is rarely useful and more often problematic, so we turn it off.
delete_merged_branches = false

# Increase timeout to 5 hours as the default timeout is too short for our build
timeout_sec = 18000
