[package]
name = "amethyst_ui"
version = "0.1.0"
authors = ["Jacob Kiesel <kieseljake@gmail.com>"]
description = "Amethyst UI crate"
keywords = ["ui", "specs", "ecs", "amethyst"]
categories = ["game-engines"]

documentation = "https://www.amethyst.rs/doc/develop/doc/amethyst_ui/index.html"
homepage = "https://www.amethyst.rs/"
repository = "https://github.com/amethyst/amethyst"
license = "MIT/Apache-2.0"

[dependencies]
amethyst_assets = { path = "../amethyst_assets", version = "0.2"}
amethyst_core = { path = "../amethyst_core", version = "0.1"}
amethyst_renderer = { path = "../amethyst_renderer", version = "0.5"}
cgmath = { version = "0.14", features = ["eders"] }
fnv = "1"
gfx = { version = "0.16", features = ["serialize"] }
gfx_glyph = "0.6"
hibitset = "0.3"
rusttype = "0.2"
shrev = "0.6"
specs = "0.10"
unicode-normalization = "0.1"
unicode-segmentation = "1.2"
winit = "0.7"
