[package]
name = "amethyst_ui"
version = "0.2.0"
authors = ["Jacob Kiesel <kieseljake@gmail.com>", "JoÃ«l Lupien <jojolepromain@gmail.com>"]
description = "Amethyst UI crate"
keywords = ["ui", "specs", "ecs", "amethyst"]
categories = ["game-engines"]

documentation = "https://www.amethyst.rs/doc/develop/doc/amethyst_ui/"
homepage = "https://www.amethyst.rs/"
repository = "https://github.com/amethyst/amethyst"
license = "MIT/Apache-2.0"

[dependencies]
amethyst_assets = { path = "../amethyst_assets", version = "0.2" }
amethyst_core = { path = "../amethyst_core", version = "0.1" }
amethyst_renderer = { path = "../amethyst_renderer", version = "0.6" }
amethyst_input = { path = "../amethyst_input", version = "0.2.1" }
clipboard = "0.4"
derivative = "1.0"
fnv = "1"
gfx = { version = "0.17", features = ["serialize"] }
gfx_glyph = "0.9.0"
hibitset = "0.3"
rusttype = "0.4"
shred = "0.5"
shred-derive = "0.3"
shrev = "0.8.1"
specs = "0.10"
unicode-normalization = "0.1"
unicode-segmentation = "1.2"
winit = "0.11.3"

thread_profiler = { version = "0.1", optional = true }

[features]
profiler = [ "thread_profiler/thread_profiler" ]
