[package]
name = "amethyst_ui"
version = "0.3.0"
authors = ["Jacob Kiesel <kieseljake@gmail.com>", "JoÃ«l Lupien <jojolepromain@gmail.com>"]
description = "Amethyst UI crate"
keywords = ["ui", "specs", "ecs", "amethyst"]
categories = ["game-engines"]

documentation = "https://www.amethyst.rs/doc/develop/doc/amethyst_ui/"
homepage = "https://www.amethyst.rs/"
repository = "https://github.com/amethyst/amethyst"
license = "MIT/Apache-2.0"

[dependencies]
amethyst_assets = { path = "../amethyst_assets", version = "0.4.0" }
amethyst_audio = { path = "../amethyst_audio", version = "0.3.0"}
amethyst_core = { path = "../amethyst_core", version = "0.3.0" }
amethyst_renderer = { path = "../amethyst_renderer", version = "0.8.0" }
amethyst_input = { path = "../amethyst_input", version = "0.4.0" }
clipboard = "0.4"
derivative = "1.0"
fnv = "1"
gfx = { version = "0.17", features = ["serialize"] }
gfx_glyph = "0.12.2"
glsl-layout = { version = "0.1.1", features = ["cgmath", "gfx"] }
hibitset = { version = "0.5.1", features = ["parallel"] }
ron = "0.4"
serde = { version = "1.0", features = ["derive"] }
shred-derive = "0.5"
shred = "0.7"
unicode-normalization = "0.1"
unicode-segmentation = "1.2"
winit = "0.17"
log = "0.4"

thread_profiler = { version = "0.3", optional = true }

[features]
profiler = [ "thread_profiler/thread_profiler" ]
nightly = [ "amethyst_core/nightly" ]
