---
display_config:
    dimensions: null
    fullscreen: false
    max_dimensions: null
    min_dimensions: null
    multisampling: 1
    title: "Sphere Example"
    visibility: true
    vsync: true
    backend: OpenGL
