[package]
name = "amethyst_core"
version = "0.1.0"
authors = ["Simon RÃ¶nnberg <seamonr@gmail.com>"]
description = "Amethyst core"

documentation = "https://www.amethyst.rs/doc/master/amethyst_core/"
homepage = "https://www.amethyst.rs/"
repository = "https://github.com/amethyst/amethyst"

license = "MIT/Apache-2.0"

[badges]
appveyor = { repository = "amethyst/amethyst" }
travis-ci = { repository = "amethyst/amethyst" }

[dependencies]
specs = "0.10"
fnv = "1.0"
cgmath = "0.14"
serde = { version = "1", features = ["serde_derive"] }
