[package]
name = "amethyst_core"
version = "0.8.1"
authors = ["Simon RÃ¶nnberg <seamonr@gmail.com>"]
edition = "2018"
description = "Amethyst core"

documentation = "https://docs-src.amethyst.rs/stable/amethyst_core/"
homepage = "https://amethyst.rs/"
repository = "https://github.com/amethyst/amethyst"

license = "MIT/Apache-2.0"

[badges]
travis-ci = { repository = "amethyst/amethyst" }

[dependencies]
nalgebra = { version = "0.18.1", features = ["serde-serialize", "mint"] }
alga = { version = "0.9.0", default-features = false }
alga_derive = "0.9.0"
approx = "0.3"
amethyst_error = { path = "../amethyst_error", version = "0.3.0" }
fnv = "1"
log = "0.4.6"
num-traits = "0.2.0"
rayon = "1.1.0"
serde = { version = "1", features = ["derive"] }
specs = { version = "0.15.1", default-features = false, features = ["shred-derive", "specs-derive"] }
specs-hierarchy = { version = "0.5.1", default-features = false }
getset = "0.0.8"
derive-new = "0.5.6"
derivative = "1.0"

thread_profiler = { version = "0.3", optional = true }

[dev-dependencies]
amethyst = { path = "..", version = "0.13.1" }
ron = "0.5.1"

[features]
default = ["specs/parallel", "specs-hierarchy/parallel"]
profiler = ["thread_profiler/thread_profiler"]
nightly = ["specs/nightly"]
saveload = ["specs/serde"]
