[package]
name = "amethyst_core"
version = "0.5.0"
authors = ["Simon RÃ¶nnberg <seamonr@gmail.com>"]
edition = "2018"
description = "Amethyst core"

documentation = "https://www.amethyst.rs/doc/latest/doc/amethyst_core/"
homepage = "https://www.amethyst.rs/"
repository = "https://github.com/amethyst/amethyst"

license = "MIT/Apache-2.0"

[badges]
appveyor = { repository = "amethyst/amethyst" }
travis-ci = { repository = "amethyst/amethyst" }

[dependencies]
nalgebra = { version = "0.16.7", features = ["serde-serialize", "mint"] }
approx = "0.3"
error-chain = "0.12"
fnv = "1"
hibitset = { version = "0.5.2", features = ["parallel"] }
log = "0.4.6"
rayon = "1.0.2"
serde = { version = "1", features = ["derive"] }
shred = { version = "0.7" }
specs = { version = "0.14", features = ["common"] }
specs-hierarchy = { version = "0.3" }
shrev = "1.0"

thread_profiler = { version = "0.3" , optional = true }

[dev-dependencies]
amethyst = { path = "..", version = "0.10.0" }

[features]
profiler = [ "thread_profiler/thread_profiler" ]
nightly = [ "shred/nightly" ]
saveload = ["specs/serde"]
