[package]
name = "amethyst_core"
version = "0.9.0"
authors = ["Simon Rönnberg <seamonr@gmail.com>", "Joël Lupien <jojolepro@jojolepro.com>", "Amethyst Foundation <contact@amethyst.rs>"]
edition = "2018"
description = "Amethyst core"

documentation = "https://docs.amethyst.rs/stable/amethyst_core/"
homepage = "https://amethyst.rs/"
repository = "https://github.com/amethyst/amethyst"

license = "MIT/Apache-2.0"

[badges]
travis-ci = { repository = "amethyst/amethyst" }

[dependencies]
nalgebra = { version = "0.19.0", features = ["serde-serialize", "mint"] }
alga = { version = "0.9.2", default-features = false }
alga_derive = "0.9.1"
approx = "0.3.2"
amethyst_error = { path = "../amethyst_error", version = "0.4.0" }
fnv = "1.0.6"
log = "0.4.8"
num-traits = "0.2.11"
rayon = "1.3.0"
serde = { version = "1", features = ["derive"] }
specs = { version = "0.16.0", default-features = false, features = ["shred-derive", "specs-derive"] }
specs-hierarchy = { version = "0.6", default-features = false }
getset = "0.0.9"
derive-new = "0.5.8"
derivative = "1.0.3"

thread_profiler = { version = "0.3", optional = true }

[dev-dependencies]
amethyst = { path = "..", version = "0.14.0" }
ron = "0.5.1"

[features]
default = ["specs/parallel", "specs-hierarchy/parallel"]
profiler = ["thread_profiler/thread_profiler"]
saveload = ["specs/serde"]
