[package]
name = "amethyst_core"
version = "0.1.0"
authors = ["Simon RÃ¶nnberg <seamonr@gmail.com>"]
description = "Amethyst core"

documentation = "https://www.amethyst.rs/doc/master/doc/amethyst_core/"
homepage = "https://www.amethyst.rs/"
repository = "https://github.com/amethyst/amethyst"

license = "MIT/Apache-2.0"

[badges]
appveyor = { repository = "amethyst/amethyst" }
travis-ci = { repository = "amethyst/amethyst" }

[dependencies]
cgmath = { version = "0.16", features = ["serde", "mint"] }
error-chain = "0.11"
fnv = "1.0"
hibitset = "0.3.2"
rayon = "1.0"
serde = { version = "1", features = ["serde_derive"] }
shred = "0.5"
specs = { version = "0.10", features = ["common"] }
quickcheck = "0.4.1"

thread_profiler = { version = "0.1" , optional = true }

[features]
profiler = [ "thread_profiler/thread_profiler" ]
