[package]
name = "amethyst_utils"
version = "0.3.0"
authors = ["Simon Rönnberg <seamonr@gmail.com>", "Joël Lupien <jojolepromain@gmail.com>"]
description = "Amethyst utils"

documentation = "https://www.amethyst.rs/doc/master/doc/amethyst_utils/"
homepage = "https://www.amethyst.rs/"
repository = "https://github.com/amethyst/amethyst"

license = "MIT/Apache-2.0"

[badges]
appveyor = { repository = "amethyst/amethyst" }
travis-ci = { repository = "amethyst/amethyst" }

[dependencies]
amethyst_assets = { path = "../amethyst_assets", version = "0.4.0" }
amethyst_controls = { path = "../amethyst_controls", version = "0.2.0" }
amethyst_core = { path = "../amethyst_core", version = "0.3.0" }
amethyst_renderer = { path = "../amethyst_renderer", version = "0.8.0" }
shred-derive = "0.5"
shred = "0.7"
serde = { version = "1.0", features = ["derive"] }

thread_profiler = { version = "0.3", optional = true }

[features]
profiler = [ "thread_profiler/thread_profiler" ]
nightly = [ "amethyst_core/nightly" ]
