[package]
name = "amethyst_context"
version = "0.1.0"
authors = ["Nikita Chashchinskii <nikita.chashinsky@yandex.ru>"]
description = "A way to manage engine resources"
keywords = ["game", "engine", "amethyst"]

documentation = "https://www.amethyst.rs/doc/amethyst/"
homepage = "https://www.amethyst.rs/"
repository = "https://github.com/amethyst/amethyst"

license = "MIT/Apache-2.0"

[dependencies.amethyst_renderer]
path = "../renderer/"
version = "0.3.0"

[dependencies.amethyst_config]
path = "../config/"
version = "0.1.0"

[dependencies.amethyst_ecs]
path = "../ecs/"
version = "0.1.0"

[dependencies]
gfx = "0.11"
gfx_core = "0.3"
gfx_device_gl = "0.10"
gfx_window_glutin = "0.11"
glutin = "0.5"
time = "0.1"
genmesh = "0.4"
cgmath = "0.7"
rodio = "0.3"
