[package]
name = "amethyst_derive"
version = "0.3.0"
authors = ["Simon RÃ¶nnberg <seamonr@gmail.com>"]
edition = "2018"
description = "Amethyst derive"

documentation = "https://docs-src.amethyst.rs/stable/amethyst_derive/"
homepage = "https://amethyst.rs/"
repository = "https://github.com/amethyst/amethyst"

license = "MIT/Apache-2.0"

[badges]
appveyor = { repository = "amethyst/amethyst" }
travis-ci = { repository = "amethyst/amethyst" }

[dependencies]
syn = { version = "0.15", features = ["visit"] }
quote = "0.6"
proc-macro2 = "0.4"

[dev-dependencies]
amethyst_core = { path = "../amethyst_core", version = "0.5.0" }
amethyst_assets = { path = "../amethyst_assets", version = "0.6.0" }
amethyst_error = { path = "../amethyst_error", version = "0.1.0" }

[lib]
name = "amethyst_derive"
proc-macro = true
