[package]
name = "amethyst_renderer"
version = "0.3.1"
authors = ["Eyal Kalderon <ebkalderon@gmail.com>"]
description = "High-level rendering engine with multiple backends"
keywords = ["game", "engine", "renderer", "3d", "amethyst"]

documentation = "https://www.amethyst.rs/doc/amethyst/"
homepage = "https://www.amethyst.rs/"
repository = "https://github.com/amethyst/amethyst"

readme = "README.md"
license = "MIT"

[dependencies]
gfx = "0.11"
gfx_core = "0.3"
gfx_device_gl = "0.10"
gfx_window_glutin = "0.11"
glutin = "0.5"
cgmath="0.11"
mopa ="0.2"

[dev-dependencies]
genmesh = "0.4"
rand = "0.3"
