[package]
name = "amethyst_input"
version = "0.6.0"
authors = ["Rhuagh <seamonr@gmail.com>", "Xaeroxe <kieseljake@gmail.com>"]
edition = "2018"
description = "Input rebinding "

documentation = "https://www.amethyst.rs/doc/latest/doc/amethyst_input/"
homepage = "https://www.amethyst.rs/"
repository = "https://github.com/amethyst/amethyst"

license = "MIT/Apache-2.0"

[badges]
appveyor = { repository = "amethyst/amethyst" }
travis-ci = { repository = "amethyst/amethyst" }

[dependencies]
amethyst_core = { path = "../amethyst_core/", version = "0.5.0" }
amethyst_config = { path = "../amethyst_config/", version = "0.9.0" }
amethyst_renderer = { path = "../amethyst_renderer/", version = "0.10.0" }
derivative = "1.0"
fnv = "1"
serde = { version = "1", features = ["derive"] }
winit = { version = "0.18.1", features = ["serde"] }
sdl2 = { version = "0.31.0", optional = true }

thread_profiler = { version = "0.3", optional = true }

[dependencies.smallvec]
version = "0.6"
features = ["serde"]

[features]
profiler = [ "thread_profiler/thread_profiler" ]
nightly = [ "amethyst_core/nightly" ]
sdl_controller = ["sdl2"]
