[package]
name = "amethyst_input"
version = "0.1.0"
authors = ["Rhuagh <seamonr@gmail.com>", "Xaeroxe <kieseljake@gmail.com>"]
description = "Input rebinding "

documentation = "https://www.amethyst.rs/doc/master/amethyst_input/"
homepage = "https://www.amethyst.rs/"
repository = "https://github.com/amethyst/amethyst"

license = "MIT/Apache-2.0"

[badges]
appveyor = { repository = "amethyst/amethyst" }
travis-ci = { repository = "amethyst/amethyst" }

[dependencies]
amethyst_core = { path = "../amethyst_core/", version = "0.1.0" }
amethyst_config = { path = "../amethyst_config/", version = "0.4.0" }
derivative = "1.0"
winit = "0.7"
fnv = "1.0"
serde = { version = "1", features = ["serde_derive"] }
shrev = "0.8"
specs = { version = "0.10", git = "https://github.com/slide-rs/specs.git" }

[dependencies.smallvec]
version = "0.4"
features = ["serde"]
